# Generated by Django 5.0 on 2023-12-13 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbot',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
