# Generated by Django 5.0 on 2023-12-13 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbot', '0002_tbot_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbot',
            name='status',
        ),
    ]
