# Generated by Django 4.2 on 2023-12-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='task_id',
        ),
        migrations.AddField(
            model_name='post',
            name='tid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='scheduled_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
