# Generated by Django 4.2 on 2023-12-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_post_task_id_post_tid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
