# Generated by Django 5.0 on 2023-12-15 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tbot', '0003_remove_tbot_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tbot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tbot.tbot', unique=True)),
            ],
            options={
                'db_table': 'channel',
            },
        ),
    ]
